### ISSUE TITLE
Error: Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by gtklocker** [EthWorks/Waffle#126]
Repo with README and steps to reproduce:

https://github.com/gtklocker/waffle-bug-report

**Comment by marekkirejczyk** [comment]
Hi @gtklocker,

Thank you for reporting. 

Fixed in [#131](https://github.com/EthWorks/Waffle/pull/131)
Released in [2.1.0](https://github.com/EthWorks/Waffle/releases/tag/2.1.0)

Closing. Please reopen if still an issue.

**Comment by rad-p** [comment]
Still have the same 
`❯ yarn test               
yarn run v1.19.1
$ waffle && mocha
Error: Cannot find module 'uuid/v4'
Require stack:
- .node_modules/ganache-core/build/ganache.core.node.js
- .node_modules/ganache-core/index.js
- .node_modules/ethereum-waffle/dist/waffle.js
- .test/basicTokenMock.js
- .node_modules/mocha/lib/mocha.js
- .node_modules/mocha/lib/cli/one-and-dones.js
- .node_modules/mocha/lib/cli/options.js
- .node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (.node_modules/ganache-core/build/webpack:/Ganache/external "safe-buffer":1:1)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1)
    at Object.<anonymous> (.node_modules/ganache-core/build/webpack:/Ganache/node_modules/ethereumjs-wallet/index.js:3:141)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1)
    at Object.GethApiDouble (.node_modules/ganache-core/build/webpack:/Ganache/lib/subproviders/geth_api_double.js:850:1)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1) 
    at Object.from (.node_modules/ganache-core/build/webpack:/Ganache/lib/subproviders/gethdefaults.js:32:1)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1)
    at Object.<anonymous> (.node_modules/ganache-core/build/webpack:/Ganache/external "web3-utils":1:1)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1)
    at Object.block (.node_modules/ganache-core/build/webpack:/Ganache/lib/utils/block_helper.js:26:1)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:1)
    at Object (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:76:55)
    at __webpack_require__ (.node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:79:1)
    at .node_modules/ganache-core/build/webpack:/Ganache/webpack/universalModuleDefinition:2:1
    at Object.factory (.node_modules/ganache-core/build/webpack:/Ganache/webpack/universalModuleDefinition:5:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at useBundled (.node_modules/ganache-core/index.js:30:22)
    at Object.<anonymous> (.node_modules/ganache-core/index.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (.node_modules/ethereum-waffle/dist/waffle.js:52:38)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (.test/basicTokenMock.js:2:68)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at .node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (.node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (.node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (.node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (.node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (.node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (.node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (.node_modules/yargs/yargs.js:1104:24)
    at Object.parse (.node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (.node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (.node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
`

**Comment by rad-p** [comment]
Fixed by
`yarn add uuid`
