### ISSUE TITLE
Decouple solcjs from waffle

### ISSUE THREAD

**Issue by robert-zaremba** [EthWorks/Waffle#194]
The waffle allows to configure the compiler (eg docker, solc-js). But the `solc-js` is somehow bundled with waffle, and there is no way use a newer version of solc-js than the one bundled in `waffle`. Would be great to decouple, and let waffle use a `solcjs` binary available in the PATH (eg node_modules/.bin when running `npx waffle` or `yarn run waffle`).

Today, the version bundled in waffle is `0.5.16`, but the latest released is `0.6.3`.

**Comment by sz-piotr** [comment]
You can use a solc binary from PATH by specifying `"compiler": "native"` in waffle config. 
Also, you should be able to specify solc compiler version in the config as `"compilerVersion".

I agree that we should probably update the dependency so that it bundles solc `0.6.x` by default!

**Comment by robert-zaremba** [comment]
I know, I was checking it. This works perfectly with `native` compiler, but does NOT work with `solcjs` (there is no way to set a custom solcjs).

**Comment by sz-piotr** [comment]
https://ethereum-waffle.readthedocs.io/en/latest/configuration.html#solcversion
You want to use `"solcVersion": "0.6.3+commit.8dda9521"`

**Comment by sz-piotr** [comment]
I was working on a better config that would make this easier, but it's still WIP #193

**Comment by robert-zaremba** [comment]
`"solcVersion": "0.6.3+commit.8dda9521" ` works. Thank you!

FYI, I also tried the following and it doesn't work:
```
{
  "compiler": "solcjs",
  "solcVersion": "./node_modules/solc"
}
```

Output:

```
npx waffle .waffle.json                                                                                                :(
AssertionError [ERR_ASSERTION]: Invalid callback object specified.
    at runWithCallbacks (/home/robert/projects/abc/node_modules/solc/wrapper.js:97:7)
    at compileStandard (/home/robert/projects/abc/node_modules/solc/wrapper.js:207:14)
    at Object.compileStandardWrapper [as compile] (/home/robert/projects/abc/node_modules/solc/wrapper.js:214:14)
    at compile (/home/robert/projects/abc/node_modules/@ethereum-waffle/compiler/dist/cjs/compileSolcjs.js:25:29) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by sz-piotr** [comment]
Hmm the fact that the `./node_modules/solc` does not work might indicate a bug
