### ISSUE TITLE
Not working on Node v10

### ISSUE THREAD

**Issue by vanruch** [EthWorks/Waffle#2]
After running `waffle` in node v10.8.0 I get the following error
```
$ waffle
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
info                 ^

 Visit Error: The module '/Users/ivan/WebstormProjects/node_modules/scrypt/build/Release/scrypt.node'
https://yarnpkg.com/en/docs/cli/runwas compiled against a different Node.js version using
 for documentation about this command.
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ivan/WebstormProjects/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
error Command failed with exit code 1.
```

Probably should rebuild the package on newer node version

**Comment by marekkirejczyk** [comment]
Should be fixed in [#5](https://github.com/EthWorks/Waffle/pull/5). Please retest and reopen if still an issue.
