### ISSUE TITLE
TypeError: promise.then is not a function. revertWith() matcher for state read contract calls.

### ISSUE THREAD

**Issue by gitpusha** [EthWorks/Waffle#210]
Hi,
I just started using buidler waffle and I really enjoy it.

I noticed one thing however for one of my solidity state read functions that is supposed to revert upon encountering a division error (using `SafeMath.sol` custom error message).

Could it be that `waffle` `chai` `matcher` `revertWith` only supports `transactions` and not contract `calls` that throw are expected to throw a  `revert` ?

The solidity source:

```
    function executorSuccessFee(uint256 _gas, uint256 _gasPrice)
        public
        view
        override
        returns(uint256)
    {
        uint256 estExecCost = _gas.mul(_gasPrice);
        return SafeMath.div(
            estExecCost.mul(executorSuccessShare),
            100,
            "GelatoExecutors.executorSuccessFee: div error"
        );
    }
```

The buidler-waffle test using the `revertedWith(message)` `chai` `matcher`:

```
    // This test does not work with chai matchers yet
    it("Shouldn't let division underflow happen", async function () {
      expect(await gelatoCore.executorSuccessFee(0, 0)).to.be.revertedWith(
        "GelatoExecutors.executorSuccessFee: div error"
      );
    });
```

The error I am getting:
```
TypeError: promise.then is not a function
at Proxy.<anonymous> (node_modules/@ethereum-waffle/chai/dist/cjs/matchers.js:40:40)
at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
at Context.<anonymous> (test/gelato_core/base/gelato_sys_admin/GelatoSysAdmin.getters.fees.test.js:44:65)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by gitpusha** [comment]
I will close this issue and reopen should I stumble across the bug again. I am currently using `3.0.2` so this issue might somewhat be deprecated.
