### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by BaldyAsh** [EthWorks/Waffle#284]
Hello, I've got this error while compiling project. Sorry, but it's impossible for me to provide you the source code, but maybe you have any idea what can produce this error?

```
* Line 1, Column 1
  Syntax error: value, object or array expected.
* Line 1, Column 2
  Extra non-whitespace after JSON value.

Error: Compilation failed
    at processOutput (/Users/anton/Developer/project/node_modules/@ethereum-waffle/compiler/dist/cjs/compiler.js:36:15)
    at compileAndSave (/Users/anton/Developer/project/node_modules/@ethereum-waffle/compiler/dist/cjs/compiler.js:17:11)
    at async Object.compileProject (/Users/anton/Developer/project/node_modules/@ethereum-waffle/compiler/dist/cjs/compiler.js:11:5)
```

**Comment by marekkirejczyk** [comment]
Looks like a bad `waffle.json` or contract compilation output. Hope its helpful
