### ISSUE TITLE
How to retrieve result of non-view function call

### ISSUE THREAD

**Issue by adamgall** [EthWorks/Waffle#339]
In solidity function calls which modify state, I'm not sure how to get the returned result of that function call.

Here is some sample code which hopefully explains what i'm talking about

`Counter.sol`
```solidity
pragma solidity >=0.4.21 <0.7.0;

contract Counter {
    uint public count;
    
    function tick() public returns (uint) {
      count++;
      return count;
    }
}

```

`Counter.test.ts`
```ts
import { expect, use } from 'chai';
import { Contract } from 'ethers';
import { deployContract, MockProvider, solidity } from 'ethereum-waffle';
import Counter from '../build/Counter.json';

use(solidity);

describe.only('Counter', () => {
  const [wallet] = new MockProvider().getWallets();
  let counter: Contract

  before(async () => {
    counter = await deployContract(wallet, Counter);
  });

  describe("the tick function", () => {
    let originalCount: Number
    let tickCount: Number
    let currentCount: Number

    before(async () => {
      originalCount = await counter.count()
      tickCount = await counter.tick()
      currentCount = await counter.count()
    })

    it("should have a starting count of 0", () => {
      expect(originalCount).to.equal(0)
    })

    it("should return the current count from the 'tick' call (or maybe not?!?!)", () => {
      console.log({ tickCount })
      expect(tickCount).to.equal(1)
    })

    it("should have an ending count of 1", () => {
      expect(currentCount).to.equal(1)
    })
  })
})
```

test results
```sh
$ npm run test

  Counter
    the tick function
      ✓ should have a starting count of 0
{
  tickCount: {
    nonce: 1,
    gasPrice: BigNumber { _hex: '0x77359400', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0xa7a2', _isBigNumber: true },
    to: '0xA193E42526F1FEA8C99AF609dcEabf30C1c29fAA',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x3eaf5d9f',
    chainId: 1337,
    v: 2710,
    r: '0x5b989a6b3bc177ff700f1be4b179bd706e2f5e124e900673917de28f49fd9c16',
    s: '0x6cce48ffd29cd9acab4315ed9888887f4c86398282c62250eb729a55d6043af8',
    from: '0x17ec8597ff92C3F44523bDc65BF0f1bE632917ff',
    hash: '0x5ce7bb6cbfd98fe0ad5d93d588cb28126333ed87ead550b723557e661cec9816',
    wait: [Function]
  }
}
      1) should return the current count from the 'tick' call (or maybe not?!?!)
      ✓ should have an ending count of 1


  2 passing (2s)
  1 failing

  1) Counter
       the tick function
         should return the current count from the 'tick' call (or maybe not?!?!):
     AssertionError: expected { Object (nonce, gasPrice, ...) } to equal 1
      at Context.<anonymous> (test/Counter.test.ts:30:41)
      at processImmediate (internal/timers.js:456:21)
```

My expectation is that `tickCount` would be equal to the returned value from the smart contract function. This is a wrong assumption. Instead, as we can see from the `console.log({ tickCount })`, the result is actually a bunch of metadata about the transaction.

[In Truffle, appending `.call()`](https://www.trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts#calls) to the end of a state-modifying function will return the "result" (without actually modifying the state).

Is there an equivalent to `.call()` in Waffle?

**Comment by adamgall** [comment]
Figured it out. It's an _Ethers.js_ thing, not a Waffle thing.

`counter.callStatic.tick()` returns a `Promise<ResultType>`, with the `ResultType` coming from the contract.

So in the test suite, I just need to update the `before()` block like so (and remove the `console.log({ tickCount })`):
```ts
before(async () => {
  originalCount = await counter.count()
  tickCount = await counter.callStatic.tick()
  await counter.tick()
  currentCount = await counter.count()
})
```

The results are now:
```sh
$ npm run test

  Counter
    the tick function
      ✓ should have a starting count of 0
      ✓ should return the current count from the 'tick' call (or maybe not?!?!)
      ✓ should have an ending count of 1

  3 passing (1s)
```

**Comment by nschwermann** [comment]
THANK YOU
