### ISSUE TITLE
abort(5) at Error

### ISSUE THREAD

**Issue by lastmjs** [EthWorks/Waffle#346]
I'm using waffle `3.0.2`, and trying to compile Chainlink's `LinkToken`. I've installed it into my `node_modules` directory with `npm install https://github.com/smartcontractkit/LinkToken.git`. I've created a custom config file for waffle:

```json
{
    "compilerType": "solcjs",
    "compilerVersion": "0.4.11",
    "sourceDirectory": "./node_modules/link_token/contracts",
    "outputDirectory": "./build"
  }
```
When I run waffle with that config, I get the following error:

```
5
5
abort(5) at Error
    at jsStackTrace (soljson-v0.4.11+commit.68ef5810.js:1:19656)
    at stackTrace (soljson-v0.4.11+commit.68ef5810.js:1:19839)
    at abort (soljson-v0.4.11+commit.68ef5810.js:19:15285)
    at Array.dXb (soljson-v0.4.11+commit.68ef5810.js:11:585101)
    at Array.tX (soljson-v0.4.11+commit.68ef5810.js:8:557453)
    at Array.eea (soljson-v0.4.11+commit.68ef5810.js:6:495332)
    at Object.wOb [as dynCall_ii] (soljson-v0.4.11+commit.68ef5810.js:11:540050)
    at invoke_ii (soljson-v0.4.11+commit.68ef5810.js:1:1275067)
    at Array.ixa (soljson-v0.4.11+commit.68ef5810.js:7:494308)
    at Object.bVb [as dynCall_viii] (soljson-v0.4.11+commit.68ef5810.js:11:577232)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```
Also I'm using Ubuntu Linux running Node.js `v12.13.1`.

**Comment by lastmjs** [comment]
It seems to only be `0.4.11` that throws the error. I'm trying it with different `0.4.x` versions and the error is not thrown

**Comment by marekkirejczyk** [comment]
Seems outdated. Closing for now. Feel free to reopen if still an issue.
