### ISSUE TITLE
calledOnContract matcher requires provider that support call history

### ISSUE THREAD

**Issue by ppedziwiatr** [EthWorks/Waffle#534]
I'm trying to use `calledOnContractWith` in a simple test:
```
const calc = (await deployContract(owner,
      FixedRatesCalculatorArtifact,
      [toWei("999"), toWei("1000")])) as FixedRatesCalculator;
    expect('setRates').to.be.calledOnContractWith(calc,[toWei("999"), toWei("1000")]);
```

I'm getting error:
```
Error: calledOnContract matcher requires provider that support call history
      at Object.ensure (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/utils.js:6:15)
      at Object.validateMockProvider (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContractValidators.js:13:13)
      at Proxy.<anonymous> (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContractWith.js:9:38)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
```

Trying to console.log here:
![image](https://user-images.githubusercontent.com/84311757/123672860-1bbfe700-d840-11eb-8178-d36aede9204d.png)

gives me:
![image](https://user-images.githubusercontent.com/84311757/123672970-35612e80-d840-11eb-93f8-f5a0113708c5.png)

deps:
```
"@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-truffle5": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
     "@typechain/hardhat": "^2.1.0",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.0.3",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.2.0",
    "hardhat": "^2.4.1"
```

**Comment by 0xlucian** [comment]
Hey @ppedziwiatr did you manage to fix that? I have the same issue trying to use this chai matcher

**Comment by ppedziwiatr** [comment]
> Hey @ppedziwiatr did you manage to fix that? I have the same issue trying to use this chai matcher

damn, that was quite a long time ago..not remember exactly, but probably not..

**Comment by crespoep** [comment]
Any updates on this issue? It still happens

**Comment by rzadp** [comment]
Currently, the `ethereum-waffle` package on its own supports the call history for Ganache providers.
In order to make this matcher work with Hardhat provider, you need to be using Waffle plugin supported by Hardhat which adds some plumbing in order to make the call history possible.

https://hardhat.org/plugins/nomiclabs-hardhat-waffle
