### ISSUE TITLE
revertedWith test passed when revert reason is different

### ISSUE THREAD

**Issue by mdatsev** [EthWorks/Waffle#608]
This example test passes, while the revert reason is different:

```solidity
function alwaysRevert() public pure {
  revert("Reason");
}
```
```js
it('Test 2', async function () {
  expect(token.alwaysRevert()).to.be.revertedWith('NOT Reason !!!');
});
```

I first encountered this when using hardhat-waffle, where the tests pass without any errors. When I tried to reproduce the bug with just waffle the test passes and then a runtime error is thrown. Output:
```
$ npm test

> ethereum-waffle-bug@1.0.0 test
> waffle && mocha test/bug.test.js



  BasicToken
    ✔ Test 1
    ✔ Test 2


  2 passing (474ms)


AssertionError: Expected transaction to be reverted with NOT Reason !!!, but other exception was thrown: RuntimeError: VM Exception while processing transaction: revert Reason
AssertionError: Expected transaction to be reverted with NOT Reason !!!, but other exception was thrown: RuntimeError: VM Exception while processing transaction: revert Reason
/mnt/d/dev/ethereum-waffle-bug/node_modules/mocha/lib/runner.js:965
    throw err;
    ^

RuntimeError: abort(AssertionError: Expected transaction to be reverted with NOT Reason !!!, but other exception was thrown: RuntimeError: VM Exception while processing transaction: revert Reason). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/mnt/d/dev/ethereum-waffle-bug/node_modules/solc/soljson.js:1:13876)
    at process.emit (node:events:402:35)
    at process.emit (/mnt/d/dev/ethereum-waffle-bug/node_modules/ganache-core/node_modules/source-map-support/source-map-support.js:465:21)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

Minimal example repo:
https://github.com/mdatsev/ethereum-waffle-bug

**Comment by akshatdev0** [comment]
@mdatsev 
You are not using it properly, these must be `await`ed.

Use the below code instead and it should work:
```
  it('Test 1', async function () {
    await expect(token.alwaysRevert()).to.be.revertedWith('Reason');
  });

  it('Test 2', async function () {
    await expect(token.alwaysRevert()).to.be.revertedWith('NOT Reason !!!');
  });

**Comment by akshatdev0** [comment]
Although, I found a similar issue while working with hardhat and waffle.
I have raised an [issue](https://github.com/nomiclabs/hardhat/issues/2234).

**Comment by trylovetom** [comment]
I have same issue here.

example code
```sol
function alwaysRevert() public pure {
  require(false, 'Saleable: insufficient funds');
}
```

```js
await expect(task).to.be.revertedWith('Saleable: insufficient funds')
```

I got this
```
AssertionError: Expected transaction to be reverted with Saleable: insufficient funds, but other exception was thrown: Error: insufficient funds for intrinsic transaction cost
```

after I change message

```sol
function alwaysRevert() public pure {
  require(false, 'Saleable: insufficient love');
}
```

```js
await expect(task).to.be.revertedWith('Saleable: insufficient love')
```

it can work fine
