### ISSUE TITLE
cb.apply is not a function error from `npx waffle`

### ISSUE THREAD

**Issue by pguardiario** [EthWorks/Waffle#610]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'waffle@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm-cache\\_npx\\93920',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.16.1
4 verbose npm-session 48f66906f1c82bbd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/waffle 40ms (from cache)
8 silly pacote tag manifest for waffle@latest fetched in 83ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npx\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:184:5)
10 verbose cwd C:\cygwin\home\User\node\waffles
11 verbose Windows_NT 10.0.19042
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js" "install" "waffle@latest" "--global" "--prefix" "C:\\Users\\User\\AppData\\Roaming\\npm-cache\\_npx\\93920" "--loglevel" "error" "--json"
13 verbose node v14.16.1
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]

**Comment by pguardiario** [comment]
This is some local npx issue, sorry.
